### ISSUE TITLE
PHP GD image manipulation library extension (gd) is not loaded.

### ISSUE THREAD

**Issue by mmttim** [tilltmk/opencats-docker#1]
Hey there,

thanks for the work! The Docker setup works, I just get this warning:

> PHP GD image manipulation library extension (gd) is not loaded.
> Check your settings in php.ini.
> 
> OpenCATS will function without GD, but no graphs will load.
> 
> Under certain Linux / BSD distributions, the PHP GD extension is a separate package.
> 
> Ubuntu: Run "apt-get install php7-gd" and restart your webserver.
> 
> Debian: Run "apt-get install php7-gd" and restart your webserver.
> 
> FreeBSD: Install the php7-gd port, or configure GD support in the php-extensions port and restart your webserver.

**Comment by tilltmk** [comment]
i remember having the same issue. try the dev branch, maybe this might fix it.

**Comment by mmttim** [comment]
This leads for me to this:

> failed to solve: process "/bin/sh -c apt-get update && apt-get install -y     libfreetype6-dev     libjpeg62-turbo-dev     libpng-dev     && docker-php-ext-configure gd --with-freetype --with-jpeg     && docker-php-ext-install g" did not complete successfully: exit code: 1

**Comment by tilltmk** [comment]
fixed, tested, works now

**Comment by tilltmk** [comment]
> fixed, tested, works now

unstable, therefore in the dev branch: 

[58482b8](https://github.com/tilltmk/opencats-docker/commit/58482b8ea2a45f90320ea3abbc107f43ef76add5)
